### ISSUE TITLE
rankAbove and rankBelow

### ISSUE THREAD

**Issue by agibson-fl** [RallyTools/RallyRestToolkitFor.NET#13]
I was wondering about the rankAbove and rankBelow fields.  The ruby project is the only rally project that implements these two calls. In fact, it goes a step further and also does rankTo which is not mentioned at all in the rally API docs.

I’m trying to use the C# rally package.  In any case, I don’t see anything mentioning rank at all in the C# documentation about rank.  No matter what I’ve done so far, I get a message that the rankAbove and rankBelow fields are ignored when the request to the API is made.

I’m building the string to pass to rally like this where above is a string containing the ID of the story I wish to rank above.
story.rankAbove = "/HierarchicalRequirement/" + above;

"Ignored JSON element HierarchicalRequirement.rankAbove during processing of this request."

That tells me that the API doesn’t accept anything for this field.  I get the same error when passing a nonsensical name.

"Ignored JSON element HierarchicalRequirement.somethingCrazyAndDoesntExist during processing of this request."

I also tried looking at the DragAndDropRank field, but that looks like it’s not human readable. 

Snippet from the rally API docs:
PUT/POST Parameters
The following parameters only have an effect for PUT and POST requests.
rankAbove, rankBelow
Set the value to an object reference url to cause the created/modified object to be ranked in relation to the referenced object.
Example: rankAbove=/slm/webservice/v2.0/defect/<Defect ObjectID>
Example: rankBelow=/slm/webservice/v2.0/defect/<Defect ObjectID>

Could you clarify?  Does this work with the Rally Ruby code?

**Comment by agibson-fl** [comment]
I don't believe this is fixed by #18.  Like I mentioned before, "the Request object appears to be used only for Get calls and not Put/Post calls which is what the rank params need".

**Comment by krmorse** [comment]
fix implemented in 3.1.1
