### ISSUE TITLE
Add NuGet package to nuget.org

### ISSUE THREAD

**Issue by masaeedu** [RallyTools/RallyRestToolkitFor.NET#24]
It would be convenient if new releases could just be downloaded from the package feed instead of having to download and commit the dlls.

**Comment by krmorse** [comment]
We agree.  We will hopefully be releasing an updated version shortly and will hopefully publish it in nuget!

**Comment by ryangribble** [comment]
Just adding support to this request.  please provide this toolkit via nuget packages!  :+1:

**Comment by jrock2004** [comment]
Any update on this?

**Comment by krmorse** [comment]
Just published version 3.1.1 to nuget!  The package is called Rally.RestApi

**Comment by ryangribble** [comment]
Hey @krmorse the project structure/dependencies contain unused references which then flows through to the nuget package as well.  It actually doesnt require any of these things

![image](https://cloud.githubusercontent.com/assets/5425163/16675247/a8dc0dde-4502-11e6-9f97-7c724760fbe5.png)

i made some changes in a fork of this repo to get a cleaner nuget publish, ill see if i can tidy them up and send a PR
