### ISSUE TITLE
AttachmentContent - Don't have project reference in the existing create method

### ISSUE THREAD

**Issue by Honeyfa** [RallyTools/RallyRestToolkitFor.NET#29]
As a user, I want to attach a content to Test Case, When I attach a content, it has only workspace reference. I don't have admin access for workspace, but I have an access for fewer projects within the workspace. So I won't able to attach the content with the workspace reference. However I can attach the content using project reference. But the Toolkit has no flexibility to pass project reference for attachmentContent.

No flexibility to accommodate the below scenario using toolkit 
using WS API, attachmentContent/Create?project=ProjectReference

**Comment by krmorse** [comment]
Implemented in 3.1.1
