### ISSUE TITLE
DoGet & DoPost in RallyRestApi.cs retry logic has infinite loop problem 

### ISSUE THREAD

**Issue by ahickey** [RallyTools/RallyRestToolkitFor.NET#30]
In the event that the error does not recover this code:

return DoGetAsPost(request, true, retryCounter++);
return DoGet(uri, true, retryCounter++);

Will always pass in retryCounter = 1 as the increment does not occur until after the function is called. 

It should be ++retryCounter.

This bug should be easy to verify by calling restApi.Authenticate with incorrect credentials.  The program will hang infinitely.

**Comment by gdmoon** [comment]
I ran into the same problem. This will cause your Rally account to be disabled if you fat finger your password.

**Comment by krmorse** [comment]
fix implemented in 3.1.1
