### ISSUE TITLE
MAX_PAGE_SIZE limited to 200

### ISSUE THREAD

**Issue by krmorse** [RallyTools/RallyRestToolkitFor.NET#40]
WSAPI actually supports 2000 now.

**Comment by krmorse** [comment]
@ferentchak, :poop:

**Comment by thunderfunkmonk** [comment]
I upped it to 2000 & added a pull request. Thanks.

**Comment by krmorse** [comment]
Fix in just released v3.3.1.  I actually just totally trashed the max page size enforcement, since WSAPI will enforce the limits, and now we don't have to change it again here in the future if it changes again.
